### ISSUE TITLE
setup docker & docker-compose correctly

### ISSUE THREAD

**Issue by albjeremias** [reel2bits/reel2bits#333]
if we achieve this, it will be easier for developers to setup a dev environment on their machines to develop faster and better ;) I'll move files, fix documentation, and make PR

**Comment by rhaamo** [comment]
moving them where ?

The documentation for prod and dev already document how to do it, dev on the root and prod in deploy.
Plus the respective Dockerfiles should stay in the respective folder they represent.

**Comment by albjeremias** [comment]
I really like the approach of mastodon... they have the docker-compose.yml and the Dockerfile on the root...
why have 2 different dockerfiles? thats more code to maintain... 

and this installation of docker described in: https://docs-develop.reel2bits.org/installation/docker.html is just a hassle... when it could be just

$ git clone repo
$ docker-compose up

**Comment by rhaamo** [comment]
dev.yml permits to have multiple instances prefixed with they own name etc. which is useful in dev.

the one in deploy only have the requirements for prod.

plus reverse proxy is different from prod and env, there is really a lot of difference when developping rather than prod.

**Comment by albjeremias** [comment]
hm, it sounds like the prod should be the default one.. and that there should be an extra one, for multiple instances? 
the reverse proxy should not be handled by reel2bits at all... all this traefik code should not belong to reel2bits

**Comment by rhaamo** [comment]
we don't use traefik but nginx, and there *is* the need for it for serving the frontend, assets or medias correctly.

there is real differences between the dev and prod docker-compose files, I prefers to have separated files to not confuse things, you either run a dev, or a prod, not doing both, and if you do both, you know what you are doing and that's not an issue.

**Comment by albjeremias** [comment]
this is what i meant about traefik.. 
https://github.com/reel2bits/reel2bits/blob/master/dev.yml#L122

**Comment by rhaamo** [comment]
@albjeremias leftover from what I've used as a base.

I will remove it later and someone can import it back if wanted.

**Comment by albjeremias** [comment]
Peertube has a structure closer to what you have.. might give inspiration:

https://github.com/Chocobozzz/PeerTube/tree/develop/support
