### ISSUE TITLE
Can't join on matrix chan :/

### ISSUE THREAD

**Issue by ImaCrea** [reel2bits/reel2bits#366]
Hi there, I'm trying to join the matrix channel but it seems I can't connect to it. Just wanted to check with you folks if it's me or if there's some issue with the matrix server :)

love the idea of reel2bits!

**Comment by rhaamo** [comment]
the domain hosting my matrix server is currently down because of issues with registrar.

I will update this issue when it comes back.

**Comment by ImaCrea** [comment]
thanks :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by rhaamo** [comment]
I think everything should be fine now

**Comment by ImaCrea** [comment]
I'm affraid nothing happens on my side when I try to add "otter.sh" to my server list in order to look for the chan then. If I try with another server it works so I guess it's not on my side :/

**Comment by rhaamo** [comment]
closing this as this should be resolved since a good time, was having some federation issues with the matrix server.
