### ISSUE TITLE
Frontend refactoring

### ISSUE THREAD

**Issue by rhaamo** [reel2bits/reel2bits#65]
Doing a massive front refactoring, including #63 would most likely require switching to a SPA like Vue.js.

However I have never touched ever Vue.js or anything like that, so...

**Comment by smonff** [comment]
:wave: I could take a look during my holidays (from 1st to 13th of July), don't hesitate to list specific problems. Though, I would have not idea what I would do since I never used Vue but who cares?

**Comment by rhaamo** [comment]
for now I'm stuck

previously with Axios I could set something like `axios.defaults.baseUrl` from the `after_store`. now with fetch I don't really know how I can do that.

my main.js creates the store as this:
https://github.com/rhaamo/reel2bits/blob/frontv2/front/src/main.js#L28

afterStore is just something which fetch nodeinfo and set various things, including the baseUrl used in dev:
https://github.com/rhaamo/reel2bits/blob/frontv2/front/src/boot/after_store.js#L58

And I have an api.service for API calls where I want to use that baseUrl (`store instanceUrl`):
https://github.com/rhaamo/reel2bits/blob/frontv2/front/src/services/api/api.service.js#L12

api.service isn't really a module, the `export default` only exports a `{list, of, functions}`, so I think I can't use getters/computed things like that.

and I would prefers having to avoid passing a store to every `apiService.doWhatever()`, but if there is no other solution I will do that.

**Comment by smonff** [comment]
I am still wanting to help: preferably on the very front-end aspect. Would you appreciate some [Bootstrap Vue](https://bootstrap-vue.js.org) integration? Or with another toolkit, I don't care... I have some experience using Reactstrap so it should be quite straightforward with the Vue equivalent. 

Otherwise, point anything that seems important to you related to the front and that you don't want to take care of. I'll take a serious look at the project tomorrow to understand better what it could need.

**Comment by rhaamo** [comment]
I always used Bootstrap, so I guess Bootstrap-vue would fit here so I don't have to learn something else.

I don't know what the others alternatives are too.

Bootstrap-vue will be useful when we will have the new design assets, for now it's more or less "X is some page, implement an API for X, then write the Vue part for that X"

For now the front does login, logout, register and that's it.

**Comment by rhaamo** [comment]
I think in order of implementation priority I would like to do:
- track upload/edit/delete
- album creation/edit/delete
- same as last but integrated in the track workflow
- user profile view/own profile edit
- various activitypub things (user followers, following, lists; following someone, unfollow, etc.)
