### ISSUE TITLE
[question] Funkwhale compatibility?

### ISSUE THREAD

**Issue by ealgase** [reel2bits/reel2bits#66]
Is this project compatible with Funkwhale (since they use the same protocols)?

**Comment by rhaamo** [comment]
AFAIK Funkwhale only federate his own type of objects (libraries).

I think there is plans to federate Audio tracks I guess, but nothing for now.

**Comment by ealgase** [comment]
Library objects contain Audio objects.  Anyway hopefully the Audio objects will also federate (or could reel2bits add Library objects?)

**Comment by rhaamo** [comment]
The two projects goals are pretty different, I'm not sure the relevance on having a full compatibility with funkwhale.

Yes I could maybe add Library if I ever manage to finish ActivityPub support at all, but that's going to be a massive stress on a reel2bits instance.

Funkwhale is, as of now, axed mostly for private libraries (the sharing function is basically just sharing with friends), plus funkwhale would need to handle publishing `Audio` with a public scope, or it will be pretty much useless.

**Comment by rhaamo** [comment]
Also funkwhale Audio is really tied to the Library thing, it would definitely needs changes on their side to federate correctly an Audio without having potentially to retrieve a whole Library collection.

**Comment by ealgase** [comment]
Yeah, implementation would require changes on both sides, but it's a cool long term goal.

**Comment by rhaamo** [comment]
Federation with Funkwhale (channels / RSS feature) is a work in progress.

Closing this issue in favor of #357
